cdapio/cdap-integration-tests

- conf/cm511.json
- conf/cm512.json
This applies the workaround recommended in https://issues.cask.co/browse/CDAP-12371 to the two CM versions that need it.  I could've added it to the template, but decided to keep it minimal in hopes this wont always be necessary.  See https://issues.cask.co/browse/CDAP-12371 for more details.
> cdap-12371 workaround for yarn.app.mapreduce.am.staging-dir

- conf/cm511.json
- conf/cm512.json
Reverts caskdata/cdap-integration-tests#837, since @chtyim has a [fix in CDAP](https://github.com/caskdata/cdap/pull/9623) for https://issues.cask.co/browse/CDAP-12371.
> Revert "cdap-12371 workaround for yarn.app.mapreduce.am.staging-dir"

- conf/dsth25.json
- conf/dsth26.json
Use HDP 2.6.2 and 2.5.6.0
http://s3.amazonaws.com/public-repo-1.hortonworks.com/index.html#/HDP/centos7/2.x/updates/2.6.2.0
caskdata/hadoop_cookbook#348 and caskdata/cdap_cookbook#260 have been merged and released
> update hdp to version 2.6.2 and 2.5.6

- conf/cloudera_manager.json
continuation of #843, the delegation token renewal settings must actually be set it 2 different safety_valves.  this PR adds the second safety_valve location, which is for the client *-site.xml given to CDAP.
This "fixes" https://issues.cask.co/browse/CDAP-12683
> set client-side delegation token renew intervals for hdfs/hbase

- conf/cloudera_manager.json
add `cdapitn` to `security.authorization.admin.users` for 4.2 certification builds.  This way, cdapitn will be an admin on the clusters spun up by the certification build.  (this is 4.2 and below)
> add security.authorization.admin.users for cdapitn for 4.2

- conf/cloudera_manager.json
overrides `sentry.service.admin.group`, to add user `cdap`.  This is needed for CDAP 4.2.
Requires https://github.com/caskdata/coopr-internal/pull/634
> add cdap user to sentry.service.admin.group

- conf/all.json
This PR reverts https://github.com/caskdata/cdap-integration-tests/pull/752 and https://github.com/caskdata/cdap-integration-tests/pull/743.
Instead, the templates are updated with these changes: https://github.com/caskdata/coopr-internal/pull/571
> Revert "Use Cask's JDK/JCE mirrors"

- conf/dstm50.json
- conf/dstm51.json
these versions were added in https://github.com/caskdata/cdap-integration-tests/pull/808 when a hive 2.0 was introduced to the repo.  This appears to have been removed, (and 1.2 updated), so just removing this constraint
> unconstrain hive version as no longer needed

- pom.xml
This is so that we can leverage the fix that happened in CDAP: https://github.com/caskdata/cdap/pull/9706.
> Update cdap.version to 4.3.2, from 4.3.0.

- integration-test-remote/src/test/java/co/cask/cdap/app/etl/batch/HivePluginTest.java
Simply use the full URI given from explore service, without stripping the scheme.
Otherwise, on some distros, there is an error saying that the URI doesn't match.
It is an error very similar to https://stackoverflow.com/questions/19431074/hive-not-fully-honoring-fs-default-name-fs-defaultfs-value-in-core-site-xml, where it is basically complaining because one of the URIs will not have the hdfs port, but the other will.
> Simply use the full URI, without stripping the scheme.

- integration-test-remote/src/test/java/co/cask/cdap/app/etl/batch/HivePluginTest.java
Otherwise, on a MapR 5.0 cluster, I was seeing the following error:
```
Caused by: org.apache.thrift.protocol.TProtocolException: Required field 'serverProtocolVersion' is unset! Struct:TOpenSessionResp(status:TStatus(statusCode:ERROR_STATUS, infoMessages:[*org.apache.hive.service.cli.HiveSQLException:Failed to open new session: java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: Error getting user info for current user, anonymous:13:12, org.apache.hive.service.cli.session.SessionManager:openSession:SessionManager.java:258, org.apache.hive.service.cli.CLIService:openSessionWithImpersonation:CLIService.java:202, org.apache.hive.service.cli.thrift.ThriftCLIService:getSessionHandle:ThriftCLIService.java:408, …
```
> Specify the user in the hive jdbc connection string.

- conf/dsth23.json
prevents `Unauthorized connection for super-user: hive from IP 10.210.0.18` happening in hdp 2.3 only.  This setting is already set in hdp 2.4+ via hadoop_wrapper krb5 attributes, as these are all kerberos-enabled
> prevent Unauthorized connection for super-user: hive

- bin/coopr-runner-wrapper.rb
JSON gem 2.0.4 in ruby 2.4.3 will generate from a string, though I can't find any supporting docs:
```
irb(main):011:0> JSON.generate('foo')
=> "\"foo\""
```
Updating previous logic that depended on the above throwing an exception, to instead explicitly check for a hash object.
> newer JSON gem will generate from a string, so updating conditional

- integration-test-core/src/main/java/co/cask/cdap/test/RemoteDatasetAdmin.java
- integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLSystemMetadataTest.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/DatasetTest.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/spark/sparkpagerank/SparkPageRankAppTest.java
- upgrade-test/src/test/java/co/cask/cdap/upgrade/MetadataUpgradeTest.java
Fix compilation errors that arose due to https://github.com/caskdata/cdap/pull/9838.
`mvn clean package -DskipTests` passed locally.
Integration Tests (Standalone): https://builds.cask.co/browse/IT-ITS1-1
> Fix compilation errors (Id-related)

- integration-test-standalone/pom.xml
Exclude guice dependency from hadoop-yarn-common project, which depends on version 3.0:
We upgraded cdap to 3.0 in https://github.com/caskdata/cdap/pull/9981.
Otherwise, when running `mvn clean test -P standalone-test`, the following error is encountered:
```
10) Error injecting method, java.lang.NoSuchMethodError: com.google.inject.spi.ProviderInstanceBinding.getUserSuppliedProvider()Ljavax/inject/Provider;
at com.google.inject.multibindings.Multibinder$RealMultibinder.initialize(Multibinder.java:324)
at co.cask.cdap.app.guice.InMemoryProgramRunnerModule.configure(InMemoryProgramRunnerModule.java:113)
Caused by: java.lang.NoSuchMethodError: com.google.inject.spi.ProviderInstanceBinding.getUserSuppliedProvider()Ljavax/inject/Provider;
at …
```
> Exclude guice dependency from hadoop-yarn-common project

- conf/cmspk20r1.json
- conf/cmspk20r2.json
- conf/cmspk21r1.json
- conf/cmspk22r2.json
- conf/cmspk23r2.json
> fix spark2 csd version

- conf/cmspk20r1.json
- conf/cmspk20r2.json
CM spark2.0 is only supported on older CDH versions as documented [here](https://www.cloudera.com/documentation/spark2/latest/topics/spark2_requirements.html#cdh_versions).  This constrains the `Spark2.0 Release1` itn to CDH 5.10.0, and the `Spark 2.0 Release 2` to CDH 5.10.x (kept it at 5.10 for consistency).
to constrain release 1 to older patch release (5.10.0), we must additionally specify the cdh parcel version (regex ok), as well as the parcel repo its available from.
> constrain cdh version for spark2.0 support

- conf/cmspk20r1.json
Fix itn cmspark2 provisioning failure.  We were unintentionally redefining a hash key.  Instead, use a comma-separated list, which `coopr_base_to_cm.rb` already supports for all cases where an argument can be specified multiple times.
> use comma-separated args for multiple arguments

- conf/dsth26.json
Bump dataset executor memory on HDP 2.6. I'm limiting this change to HDP 2.6, since other distros don't seem to be having their dataset executors being killed for going over the configured memory of 512mb.
We can investigate further if there is something unique to HDP 2.6 that is causing this issue.
> Bump dataset executor memory on HDP 2.6.

- integration-test-remote/src/test/java/co/cask/cdap/operations/OperationalStatsTest.java
Removed integration tests due to functionality removed in https://issues.cask.co/browse/CDAP-13493.
> CDAP-13493 Remove integration tests for Hadoop operational stats.

- conf/dsth26.json
I'm limiting this change to HDP 2.6, since other distros don't seem to be having their dataset executors being killed for going over the configured memory of 512mb.
We can investigate further if there is something unique to HDP 2.6 that is causing this issue.
This is similar to: https://github.com/caskdata/cdap-integration-tests/pull/912
> Bump messaging service memory on HDP 2.6.

- conf/cdap.json
- conf/dsth26.json
Apply the changes from https://github.com/caskdata/cdap-integration-tests/pull/916 and https://github.com/caskdata/cdap-integration-tests/pull/912 to all distros.
> Bump container memory

- conf/all.json
JDK7 is EOL.  Previously, builds were failing to download maven artifacts due to a handshake failure, even when forcing TLS v1.2.
> update builds to jdk 8 to avoid https handshake failure

- conf/ambh24.json
- conf/ambh25.json
- conf/ambh26.json
Update to the latest Ambari versions. 
- The coopr_base_to_ambari.rb will always install the default HDP version. 
- Previously the Ambari versions were 1 minor version behind HDP. With the release of Ambari 2.6, they caught up to HDP
- HDP 2.6.5 comes with Spark 2.3 which is NOT currently supported. I'll disable ITN for Ambari 2.6.2 until this is supported.
Ambari ITN |   |  
-- | -- | --
ambari version | default hdp version | Spark version
2.6.2 | 2.6.5 | 2.3/1.6
2.5.2 | 2.6.3 | 2.2/1.6
2.4.3 | 2.5.3 | 2.0/1.6
> update ambari versions

- integration-test-remote/src/test/java/co/cask/cdap/apps/workflow/WorkflowTest.java
Similar pattern as in https://github.com/caskdata/cdap-integration-tests/pull/927.
My understanding is that the workflow token won't be available instantly, the moment the workflow completes. Instead, a retry needs to be done, while waiting for the workflow token is available.
> Attempt at fixing flaky WorkflowTest#testLDA

- integration-test-remote/src/test/java/co/cask/cdap/apps/workflow/WorkflowTest.java
In https://github.com/caskdata/cdap-integration-tests/pull/929, we attempted to use `Tasks.waitFor` to retry the workflow token checks. However, it only retries on return value differences, and not on exceptions thrown.
> Retry workflow token assertions on exceptions.

- integration-test-core/src/main/java/co/cask/cdap/test/Tasks.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/ProgramMetadataApp.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/ProgramMetadataTest.java
- integration-test-remote/src/test/java/co/cask/cdap/test/suite/AllTests.java
- In 5.0 we introduced the capability to read/emit metadata from programs
- This PR introduces a MR job reading/emitting metadata for testing purposes
> CDAP-13261 Add integration test for testing metadata from programs

- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/ProgramMetadataStressApp.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/ProgramMetadataStressTest.java
- Adds an app for testing which emits lots of metadata from program container
- The goal is to make sure CDAP is functional and does not crash specifically dataset op executor container.
- Currently the load is very low as our clusters are small.
- TODO: This test should run it's own suite which only runs on large cluster
> CDAP-13261 Metadata Stress Test

- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java
**Summary**
`PurchaseMetadataTest#testLineage()` test is flaky. The test fails to assert metadata for second run of the service. One potential fix is to wait more for the metadata since `getMetadata()` call  for program runs first queries Lineage store for runid and then metadata store. 
ITN Mini: https://builds.cask.co/browse/IT-ITM5-2
> Add assert for tags and props in PurchaseMetadataTest#testLineage

- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java
LOG the runID so that when the flaky failure happens we can verify that the get is happening for the correct runId
> LOG purchase history service run id

- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java
[CDAP-13721](https://issues.cask.co/browse/CDAP-13721) Deprecates Metadata aggregration for RunId
> Remove RunId metadata assertion

- integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLTestBase.java
In PR https://github.com/caskdata/hydrator-plugins/pull/852 
We removed the deprecated HDFS plugin so the test setup should not depend on it.
> CDAP-14529 Remove check for hdfs plugin

- integration-test-remote/src/test/java/co/cask/cdap/app/etl/GCSTest.java
Use File sink plugin instead of HDFSSink plugin, for GCSTest.
HDFS sink was deprecated (https://github.com/caskdata/hydrator-plugins/pull/787) and removed (https://github.com/caskdata/hydrator-plugins/pull/852).
> Use File sink plugin instead of HDFSSink plugin, for GCSTest.

- pom.xml
It was renamed in https://github.com/caskdata/cdap/pull/10677.
> Update the program report app dependency module name.

- upgrade-test/src/test/java/co/cask/cdap/upgrade/MetadataUpgradeTest.java
We don't index application with stream names and haven't in past either.
> Fix metadata result assertion for stream

- upgrade-test/src/test/java/co/cask/cdap/upgrade/LineageUpgradeTest.java
frequentCustomers dataset is used here 
https://github.com/caskdata/cdap/blob/61c3850192e2bf5d2230fe8b7cc40e247b50aac5/cdap-examples/Purchase/src/main/java/co/cask/cdap/examples/purchase/PurchaseHistoryBuilder.java#L104
> Fix LineageUpgradeTest asserstion

- conf/autobuild_skip.json
In some rare cases, it is desirable to disable autobuild for an ITN build, such as the "pre" step of the upgrade test.  This PR adds a config to disable autobuild, that can be optionally included by coopr-runner-wrapper via the `COOPR_RUNNER_WRAPPER_EXTRA_DIMENSIONS` environment variable
> add optional config to skip autobuild via extra dimensions

- integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLSystemMetadataTest.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/ProgramMetadataTest.java
after the change in cdap, metadata is now written via TMS, and we need to waitFor() it to show up.
> [CDAP-14587] Make metadata tests wait for async metadata update

- integration-test-remote/src/test/java/co/cask/cdap/operations/OperationalStatsTest.java
Only line 57 was failing, but I'm proactively also removing line 56.
Example failure: https://builds.cask.co/browse/IT-ITN-DSTM51-189/test/case/72349325
```
java.lang.NullPointerException: null
at co.cask.cdap.operations.OperationalStatsTest.toInt(OperationalStatsTest.java:75)
at co.cask.cdap.operations.OperationalStatsTest.testCDAPStats(OperationalStatsTest.java:57)
```
> Update OperationalStatsTest to remove assertion on streams.

- integration-test-remote/src/test/java/co/cask/cdap/apps/ApplicationTest.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/fileset/FileSetExample.java
Fix ApplicationTest by migrating it to use an application that doesn't use Flow.
Fixes the following failure:
https://builds.cask.co/browse/IT-ITN-DSTH22-204/test/case/72348811
```
java.lang.RuntimeException: java.io.IOException: co.cask.cdap.api.flow.Flow
at co.cask.cdap.client.util.RESTClient.upload(RESTClient.java:160)
at co.cask.cdap.client.ApplicationClient.deployApp(ApplicationClient.java:449)
at co.cask.cdap.client.ApplicationClient.deploy(ApplicationClient.java:377)
at co.cask.cdap.client.ApplicationClient.deploy(ApplicationClient.java:353)
at co.cask.cdap.test.IntegrationTestManager.deployApplication(IntegrationTestManager.java:183)
at co.cask.cdap.test.AbstractTestManager.deployApplication(AbstractTestManager.java:43)
at …
```
> Fix ApplicationTest by migrating it to use an application that doesn't use Flow.

- integration-test-remote/src/test/java/co/cask/cdap/apps/dataset/DatasetTest.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/dataset/RetrieveCounts.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/dataset/RetrieveCountsHandler.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/dataset/WordCount.java
- integration-test-remote/src/test/java/co/cask/cdap/test/suite/AllTests.java
This tests all the functionality of the original test, but instead of populating the table via the stream/flow in the example, we simply write to it via AudiTestBase.
> Add dataset test with modified example.

- integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLTestBase.java
Use the Cask Market base url from cdap-site, instead of hardcoding it in the tests.
> Use the Cask Market base url from cdap-site, instead of hardcoding it in the tests.

- integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLSystemMetadataTest.java
- integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/ProgramMetadataTest.java
Change MetadataClient usage, as per changes in https://github.com/cdapio/cdap/commit/ec750e04834f7c312b3fe4cdeb694c8d79bea084#diff-b4114e6a647587816791abcd9ef15f72.
Otherwise, builds can fail with compilation errors, such as in https://builds.cask.co/browse/IT-CLD-215/log
or such as in https://builds.cask.co/browse/IT-IIT-285/log
> Change MetadataClient usage, since the API changed

- integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLTestBase.java
HivePluginTest fails across the board after changing to use the new CDAP Hub on GCS: https://builds.cask.co/browse/IT-ITN-281
This is because GCS does not ignore any authentication tokens that are provided in headers, and instead fails the request if they are passed in. The fix is to not pass in any such headers, as Hub does not require authentication.
Test passes after this change: https://builds.cask.co/browse/IT-ITCC9-4
> Avoid using auth token for REST calls to CDAP Hub.

- conf/cdap.json
- conf/cdap_mapr.json
- conf/cdap_sdk.json
ITN clusters are autobuilt, but there is logic in the cdap cookbook that keys off this version attribute.  Bump it to 6.0 for new cookbook logic.
> bump version attribute for cookbook logic

- pom.xml
JIRA: https://issues.cask.co/browse/CDAP-15756
In the scope of this PR:
- fixed inability to start spanned tests
> CDAP-15756 GoogleCloudSpannerTest broken due to pubsub dependency

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleCloudSpannerTest.java
Fix checkstyle; ITN build is failing across all distros.
The failure is likely due to https://github.com/cdapio/cdap-integration-tests/pull/1023
```
$ mvn clean package -DskipTests
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] integration-test 1.0.0 ............................. SUCCESS [02:11 min]
[INFO] integration-test-core .............................. SUCCESS [  3.951 s]
[INFO] integration-test-remote ............................ SUCCESS [  6.022 s]
[INFO] integration-test-standalone ........................ SUCCESS [  0.833 s]
[INFO] upgrade-test ....................................... SUCCESS [  0.654 s]
[INFO] long-running-test .................................. SUCCESS [  1.461 s]
[INFO] perf-test 1.0.0 …
```
> Fix checkstyle; ITN build is failing across all distros.

- integration-test-core/src/main/java/io/cdap/cdap/test/AudiTestBase.java
We've noticed Spark streaming program take >60 seconds to go into RUNNING state, where in the previous run, it took ~40 seconds.
> Increase default program timeout to 120 seconds.

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudBigtableTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudDatastoreTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudSpannerTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/test/suite/GCPSuite.java
Fixed the bigtable test to create an instance at the start of the
tests instead of requiring that an instance is already setup.
Added artifact info to all of the pipelines so that they are
viewable through the UI.
> Create a GCP test suite and fix tests to set project for plugins

- conf/cdap.json
CDAP services are getting killed by yarn due to physical memory
constraints. Disable the pmem check to avoid this.
> disable yarn pmem check

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudDatastoreTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudSpannerTest.java
Enhanced bigquery, datastore, and spanner tests to use macros.
> CDAP-15804 use macros in tests for gcp plugins

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudDatastoreTest.java
Checking metrics is very unreliable due to race conditions. It can
fail incorrectly because they are not polled for a long enough time,
and they can pass incorrectly because the number being checked is
too low.
> remove datastore metric assertions

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java
The pubsub test was flaky because it would occasionally get a 400
error that the pipeline is not running when the stop call is made.
Changed the test to just log a warning in this scenario since the
test was actually successful. CDAP may have some underlying bugs
causing this behavior though.
> CDAP-16429 log a warning if pipeline cleanup fails

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/ETLTestBase.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/HivePluginTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/hub/PluginAttributes.java
Fix the deploy hub plugin method to use the public CDAP REST APIs
instead of some UI endpoint that is subject to change and which is
currently broken.
> CDAP-16430 fix deploy hub plugin

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
Add a way to modify the dataproc worker cpus and memory through
passing in system properties. Also set the default to a higher
value, since some pipelines seem to be stuck waiting for
resources.
> make dataproc worker resources configurable

- integration-test-remote/src/test/java/io/cdap/cdap/test/suite/GCPSuite.java
Explicitly listing out tests in the GCP suite to control the
order and see if some failures can be explained by ordering.
> explicitly list tests in the GCP suite

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
This fixes an issue where some pipelines in some environments
are stuck forever with MapReduce jobs that stay in pending state.
> increase dataproc cluster size

- integration-test-remote/pom.xml
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DLPTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudSpannerTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/test/suite/GCPSuite.java
- pom.xml
Fix the google library dependencies to versions that all use
compatible dependencies, and remove the direct gax-grpc depdendency
that was causing Spanner to fail.
Also use macros in the BQ tests to both test macros and to
workaround an issue when the CDAP instance is running on a GCE
VM.
> fix integration tests

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DLPTest.java
Fixed the dlp test, which was incorrectly counting an empty file
as an output line of an empty string.
> CDAP-16604 fix dlp test

- integration-test-remote/pom.xml
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryMultiSinkTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryUtils.java
- pom.xml
Add integration tests for BQMultiSink
- Updated dependencies to use latest version from respective develop branches
- Refactored GoogleBigQueryUtils to move common code to utility class
- Covers the following tests
1. Read from two sources and add to two new tables
2. Read from two sources and add to two existing tables
3. Read from two sources and add to two existing tables with truncate_table set
4. Read from two sources and add to two existing tables with schema modification
5. Read from one and write to one table - This doesn't work right now due to  https://issues.cask.co/browse/PLUGIN-402
> Integration tests for BQ Multisink

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudSpannerTest.java
- pom.xml
In some slow instance and network, seeing the metrics doesn't get published within the original timeout, so increasing the timeout of it.
> Bump version and fix spanner

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DLPTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudBigtableTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudDatastoreTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudSpannerTest.java
The cloud itn is failing since we recently made a change to run the pipeline with both mapreduce and spark engines, this made the test fail because the pipeline checks for metrics, update schema of the table in the run. So second run will fail with metrics check failure or program run failure or app deploy failure. 
Have run at least one test from each class on sandbox to make sure the changes are working.
> Cdap 17543 fix cloud itn

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryUtils.java
Added: Test BigQuery Sink when destination table does not exist, partition type is INTEGER, and partition field is macro
Added: Test BigQuery Sink when destination table does exist, partition type is INTEGER, and partition field is macro
Jira Ticket: https://cdap.atlassian.net/browse/PLUGIN-517
PR: https://github.com/data-integrations/google-cloud/pull/553
> PLUGIN-517

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/ExcelInputReaderTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/XMLReaderTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/realtime/DataStreamsTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/wrangler/WranglerServiceTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/serviceworker/ServiceWorkerTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/apps/ApplicationTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/apps/NamespaceTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/apps/fileset/PartitionCorrectorTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/apps/fileset/PartitionedFileSetUpdateTest.java
New ITN system was throwing errors because some post/put errors did not set the `content-length` header. I updated the tests to include an empty string as body to set the length header in the request.
Also removed Assert checks on exact error messages but left checks on error codes
> Update tests to be compatible with new ITN system

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/ETLMapReduceTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/HivePluginTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/apps/fileset/PartitionCorrectorTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/apps/fileset/PartitionedFileSetUpdateTest.java
Explore relies on an old Hive version and isn't being used now.
> Disable tests that use explore functionality

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java
This test has the same service account path issue that was addressed in #1106 but it was missed in that PR.
> Fix GCSTest.testCreateFileMarkerOnPipelineFailure

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java
Jira: https://cdap.atlassian.net/browse/PLUGIN-594
CSV Schema Detection Integration tests for:
- A single file path
- A path containing multiple files with different schema
- A path containing multiple files with different schema + regex expression provided
- A path containing multiple files with different schema without Header
> Add integration tests for CSV Schema Detection (with GCSSource Plugin)

- integration-test-remote/src/test/java/io/cdap/cdap/app/fileset/PermissionTest.java
Disabling dynamic partitioning checks until the feature is fixed
in CDAP.
> CDAP-17747 disable dynamic partitioning checks

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
BigQuery sink will fail to commit the job if there are two input sources with different schema record name
Cherrypicks: 
-> https://github.com/data-integrations/google-cloud/pull/629
-> https://github.com/data-integrations/google-cloud/pull/630
-> https://github.com/data-integrations/google-cloud/pull/631
JIRA Ticket: http://issues.cask.co/browse/PLUGIN-624
> [PLUGIN-624] Integration test - BigQuery sink will fail to commit the job if there are two input sources with different schema record name

- pom.xml
Update snapshot version for dependencies for develop after 6.5 branch is cut
> Update snapshot version for dependencies for develop after 6.5 branch is cut

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java
- pom.xml
- Fix for  https://cdap.atlassian.net/browse/CDAP-18250
- Correct test data to add missing column
- Fix test data to not add header to match test expectation
- Set `forkCount` to 1 as a possible fix for https://cdap.atlassian.net/browse/CDAP-18281
> Fix GCSTest#testSchemaDetectionOnMultipleFilesWithDifferentSchema

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
Integration tests are currently failing because of pipeline taking longer time to complete. The longer duration is causing the tests to timeout and not wait for pipeline completion. This is creating cascading issues as the dataproc profile cannot be cleaned up after the test has run.
Increasing wait time for pipeline completion as a short term fix.
> CDAP-18718: Increasing wait time for pipeline completion

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java
PubSubTest was disabled because of the below error
2021-07-16 17:09:49,074 - ERROR [Driver:o.a.s.d.y.ApplicationMaster@94] - User class threw exception: java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/HAUtil
java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/HAUtil
at org.apache.twill.filesystem.FileContextLocationUtil.lookupInHAUtil(FileContextLocationUtil.java:42) ~[org.apache.twill.twill-yarn-0.14.0.jar:0.14.0]
at org.apache.twill.filesystem.FileContextLocationUtil.<clinit>(FileContextLocationUtil.java:52) ~[org.apache.twill.twill-yarn-0.14.0.jar:0.14.0]
The issue is now fixed so re-enabling this test.
Jira - https://cdap.atlassian.net/browse/CDAP-18241
> Enable PubSubTest

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java
PubSubTest was disabled because of the below error
```
2021-07-16 17:09:49,074 - ERROR [Driver:o.a.s.d.y.ApplicationMaster@94] - User class threw exception: java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/HAUtil
java.lang.NoClassDefFoundError: org/apache/hadoop/hdfs/HAUtil
at org.apache.twill.filesystem.FileContextLocationUtil.lookupInHAUtil(FileContextLocationUtil.java:42) ~[org.apache.twill.twill-yarn-0.14.0.jar:0.14.0]
at org.apache.twill.filesystem.FileContextLocationUtil.<clinit>(FileContextLocationUtil.java:52) ~[org.apache.twill.twill-yarn-0.14.0.jar:0.14.0]
```
The issue is now fixed so re-enabling this test.
Jira - https://cdap.atlassian.net/browse/CDAP-18241
> Enable PubSubTests

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java
Reverts cdapio/cdap-integration-tests#1167
Reverting the enabling of pub/sub tests as they seem flaky causing cloud-itn-failures.
> Revert "Enable PubSubTests"

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
Dataproc clusters created to run the integration tests use default compute engine service account, which has excessive permissions. 
Add service account property to dataproc profile created for running pipelines.
> Add serviceAccount property to Dataproc profile

- pom.xml
cdap-cli 6.7.3-SNAPSHOT has changes to ProgramClient from https://github.com/cdapio/cdap/pull/14935
> Update cdap version to 6.7.3-SNAPSHOT to get updated cdap-cli dependency which fixes test flakiness

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java
PubSub could publish messages more than once occasionally. Consider this while checking for pipeline results.
> Add additional log for message publish status and fix the check for messages

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/wrangler/WranglerTest.java
This PR adds integration tests for filtering using SQL expressions for Wrangler. Filtering using Spark SQL engine is tested in `WranglerTest` while filtering using BQ engine is tested in `GoogleBigQuerySQLEngineTest`.
> Add integration tests for Wrangler filtering

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
Reverts cdapio/cdap-integration-tests#1240
This does not work due to https://cdap.atlassian.net/browse/CDAP-20782.
> Revert "Skip cluster deletion to prevent long-running tests bottlenecked by Dataproc cluster creation time"

- integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
Switch remote tests to use e2 machine types
cherry-pick #1244
> Switch remote tests to use e2 machine types
