cdapio/cdap-integration-tests

conf/ambari.json

Bump the Ambari service to use 5.0.0

Version bump the CDAP Ambari service

---

conf/cloudera_manager.json

backport of #856, no conflicts

add security.authorization.admin.users for cdapitn for 4.2

---

conf/dstm50.json
conf/dstm51.json

cherry-pick #864, no conflicts

unconstrain hive version as no longer needed

---

integration-test-remote/pom.xml
integration-test-remote/src/test/java/co/cask/cdap/security/AppImpersonationAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/AuthorizationTestBase.java
integration-test-remote/src/test/java/co/cask/cdap/security/AuthorizationTestClient.java
integration-test-remote/src/test/java/co/cask/cdap/security/BasicAppAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/BasicAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/CustomMappingAppAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/CustomMappingBasicAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/NamespaceImpersonationAppAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/NamespaceImpersonationBasicAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/RangerAuthorizationClient.java
integration-test-remote/src/test/java/co/cask/cdap/security/RangerAuthorizationClientTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/RangerAuthorizationTestClient.java
integration-test-remote/src/test/java/co/cask/cdap/security/SentryAuthorizationTestClient.java
integration-test-remote/src/test/java/co/cask/cdap/security/SentryBasicAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/test/suite/AuthorizationTests.java
integration-test-remote/src/test/java/co/cask/cdap/test/suite/SentryAuthorizationSuite.java

Ranger part is based on the feature_release/migrate-new-tests-ranger created by Rohit

refactor and combine tests with ranger

---

integration-test-remote/src/test/java/co/cask/cdap/app/etl/batch/ETLMapReduceTest.java

Remove usage of error dataset in integration test and replace with
an error collector.

CDAP-11870 replace error dataset with error collector

---

conf/ambari.json

set security.keytab.path 
security.authorization.extension.jar.path overwrites the template setting the latest jar for release 4.3

update auth properties

---

integration-test-remote/src/test/java/co/cask/cdap/security/BasicAppAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/BasicAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/NamespaceImpersonationBasicAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/SentryBasicAuthorizationTest.java

It is better we put a sleep after each pre-grant to avoid race condition

Add a sleep after each pre-grant

---

conf/dsth26.json

update hdp 2.6 to use 2.6.3

---

integration-test-remote/src/test/java/co/cask/cdap/app/etl/batch/HivePluginTest.java
integration-test-remote/src/test/java/co/cask/cdap/apps/fileset/FileSetTest.java
integration-test-remote/src/test/java/co/cask/cdap/test/suite/AllTests.java
long-running-test/src/test/java/co/cask/cdap/longrunning/datacleansing/DataCleansingTest.java

Add integration test for HiveImport plugin.
Shouldn't be merged until https://github.com/caskdata/coopr-internal/pull/650 is merged and active on provisioned clusters.

Add integration test for HiveImport plugin.

---

conf/dsth23.json

Backport #881 to release/4.3.  No conflicts

prevent Unauthorized connection for super-user: hive

---

bin/coopr-runner-wrapper.rb

Backport of #889, no conflicts

newer JSON gem will generate from a string, so updating conditional

---

integration-test-remote/src/test/java/co/cask/cdap/security/AuthorizationTestBase.java
integration-test-remote/src/test/java/co/cask/cdap/security/BasicAppAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/BasicAuthorizationTest.java

Added a stream auth test to avoid CDAP-13123

add stream authorization exploration test

---

conf/ambari.json

bump the expected version of the cdap-ranger-binding jar

bump expected version of cdap-ranger-binding jar

---

bin/coopr-runner.rb

Adds a retry mechanism to Coopr client calls, to retry until they complete without exception (the ruby rest-client library throws an exception on non-ok).  This same mechanism already in use internally for the cm/ambari automator scripts:  https://github.com/caskdata/coopr-internal/pull/542 (private repo).

add retry mechanism to coopr client

---

conf/cm513.json
conf/cm514.json
conf/dstc513.json
conf/dstc514.json

adds ITN configs for CDH 5.13 and 5.14
https://www.cloudera.com/documentation/enterprise/release-notes/topics/cdh_vd_cdh_package_tarball.html

add cdh 5.13 and 5.14

---

conf/ambari.json
integration-test-remote/src/test/java/co/cask/cdap/app/etl/batch/HivePluginTest.java
integration-test-remote/src/test/java/co/cask/cdap/apps/fileset/FileSetTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/AuthorizationTestBase.java
integration-test-remote/src/test/java/co/cask/cdap/security/BasicAppAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/security/BasicAuthorizationTest.java
integration-test-remote/src/test/java/co/cask/cdap/test/suite/AllTests.java
long-running-test/src/test/java/co/cask/cdap/longrunning/datacleansing/DataCleansingTest.java

```
$ mvn clean package -DskipTests
...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] integration-test ................................... SUCCESS [  4.228 s]
[INFO] integration-test-core .............................. SUCCESS [  2.649 s]
[INFO] integration-test-remote ............................ SUCCESS [  5.053 s]
[INFO] integration-test-standalone ........................ SUCCESS [  0.739 s]
[INFO] upgrade-test ....................................... SUCCESS [  0.732 s]
[INFO] long-running-test .................................. SUCCESS [  0.893 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] …
```

Merge release/4.3 to develop

---

pom.xml

ITN is failing because it is not using latest tracker

Update tracker version to latest

---

conf/cm515.json
conf/dstc515.json

add cm 5.15

---

conf/ambari.json

version bump ambari repo

---

integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java

The reason for this change is there is a race condition in updating the run records and lineage metadata since they are 2 different tables. Now lineage access table creates 2 entries for a dataset: first one with unknown access type and second with read/write access type. This the second entry is not present when integration test queries it, this `PurchaseMetadataTest` can fail. So we should retry for lineage. 
I have tested the fix on the failure cluster.

Retry lineage query in case of race condition.

---

conf/autobuild.json

Add mmds and dre to auto build. 
cdap-build: https://github.com/caskdata/cdap-build/pull/54

CDAP-13533

---

integration-test-remote/src/test/java/co/cask/cdap/app/etl/GCSTest.java

Accept google application credentials directly as a system property, instead of reading from the file system.
We accept the credentials as base64-encoded, because otherwise, it is difficult to pass the credentials on the commandline:
```
error	24-Jul-2018 18:41:24	Unable to parse command line options: Unrecognized option: -----BEGIN PRIVATE KEY-----  ...
```

Accept google application credentials directly as a system property

---

conf/cloudera_manager.json

analagous to caskdata/cdap-integration-tests#918

increase memory lower-bound for all containers in cm clusters

---

integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLTestBase.java

This resolves failures such as: https://builds.cask.co/browse/IT-CLD1-7
The master logs indicate that the application deploy happened after some artifacts were loaded, but not all of them:
There is logic in the integration test framework to wait until some artifacts are loaded (core-plugins), but not all of them: https://github.com/caskdata/cdap-integration-tests/blob/release/5.0/integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLTestBase.java#L97

Also wait for HDFS plugins in ETLTestBase.

---

conf/cdap_sdk.json

update CDAP SDK version to 5.1

---

integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java

Context: In https://github.com/caskdata/cdap-integration-tests/pull/927, one lineage assertion was changed to retry. However, the test case still failed at a different assertion: https://github.com/caskdata/cdap-integration-tests/blob/release/5.0/integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java?utf8=%E2%9C%93#L286
So, I'm applying the retry logic to more places.
The changes are not done yet, but opening PR for feedback.
I'm uncertain whether we need to retry all of these types of operations, especially the `searchMetadata` operations.

Retry metadata/lineage in more places.

---

integration-test-remote/src/test/java/co/cask/cdap/apps/workflow/WorkflowTest.java

https://issues.cask.co/browse/CDAP-14132
Update the integration test, similar to how the unit test was updated for WikipediaPipelineAppTest in https://github.com/caskdata/cdap/pull/10538/files/ce178dd9a1fcb77bdc77f15e8605a8105bb74567#diff-3845df6cbb9ec56ff7404fee98ca9608.

CDAP-14132 Update the integration test, due to the examples being bumped to Spark2

---

integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java

Cherry-pick changes to release/5.1

Cherry-pick changes to release/5.1

---

conf/ambari.json

Bump Ambari version on develop

Bump Ambari version on develop

---

conf/ambari.json

Version bump the CDAP version for Ambari.

version bump CDAP for Ambari

---

integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/PurchaseMetadataTest.java

In https://github.com/cdapio/cdap/pull/10854, support for stream/view metadata was removed.
So, removing the relevant integration test code.
I filed https://issues.cask.co/browse/CDAP-14611 to bring back tests for some functionality (search by field name and TTL).

Remove test cases that test stream/view metadata.

---

integration-test-remote/src/test/java/co/cask/cdap/apps/spark/SparkPageRankApp.java
integration-test-remote/src/test/java/co/cask/cdap/apps/spark/SparkPageRankAppTest.java
integration-test-remote/src/test/java/co/cask/cdap/apps/spark/SparkPageRankProgram.java
integration-test-remote/src/test/java/co/cask/cdap/test/suite/Spark2Tests.java

Remove stream input and read from dataset

Migrate spark page rank app to ITN

---

integration-test-remote/src/test/java/co/cask/cdap/app/etl/ETLSystemMetadataTest.java
integration-test-remote/src/test/java/co/cask/cdap/apps/metadata/ProgramMetadataTest.java

Fix compilation, as a result of https://github.com/cdapio/cdap/pull/10925.

Fix compilation, as a result of https://github.com/cdapio/cdap/pull/10925

---

integration-test-remote/src/test/java/co/cask/cdap/app/etl/wrangler/WranglerServiceTest.java

Updated the wrangler service test to use the namespaced endpoints
in the system namespace.

CDAP-14764 update wrangler service test to use namespaces

---

integration-test-remote/src/test/java/co/cask/cdap/app/etl/GCSTest.java

This is similar to the change here: https://github.com/cdapio/cdap-integration-tests/pull/941
This fixes the following issue (such as in https://builds.cask.co/browse/IT-CLD-188/test or https://builds.cask.co/browse/IT-CLD-189/test):
```
java.io.IOException: No plugin of type action and name GCSCopy could be found for stage cp1.
at co.cask.cdap.client.util.RESTClient.upload(RESTClient.java:160)
at co.cask.cdap.client.ApplicationClient.deploy(ApplicationClient.java:410)
at co.cask.cdap.test.IntegrationTestManager.deployApplication(IntegrationTestManager.java:200)
at co.cask.cdap.test.IntegrationTestBase.deployApplication(IntegrationTestBase.java:377)
at co.cask.cdap.app.etl.GCSTest.testGCSCopy(GCSTest.java:310)
```
The application deploy failed because it was looking for a plugin that was …

Wait for google-cloud plugins to load before running GCS test cases.

---

integration-test-remote/src/test/java/co/cask/cdap/apps/workflow/WorkflowAppWithFork.java
integration-test-remote/src/test/java/co/cask/cdap/apps/workflow/WorkflowTest.java
integration-test-remote/src/test/java/co/cask/cdap/test/suite/AllTests.java

Tests a simple workflow which starts up, forks, and writes to datasets.

Re-add workflow test to ITN.

---

integration-test-remote/src/test/java/io/cdap/cdap/remote/dataset/test/RemoteCubeTest.java

Fix compilation which broke after https://github.com/cdapio/cdap/pull/11435
Example failed build: https://builds.cask.co/browse/IT-ITN-294/log

Fix compilation which broke after https://github.com/cdapio/cdap/pull/11435

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/GCSTest.java

Added tests for GCS Move, Delete and Create actions.

CDAP-15640 GCS integration tests coverage

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleCloudSpannerTest.java
pom.xml

JIRA: https://issues.cask.co/browse/CDAP-15641
In the scope of this PR:
* Created Spanner integration tests
Currently, two tests fail because of https://issues.cask.co/browse/CDAP-15724.
Fixed by: https://github.com/data-integrations/google-cloud/pull/133

CDAP-15641 Spanner integration tests

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/PubSubTest.java
integration-test-remote/src/test/resources/logback-test.xml
pom.xml

JIRA: https://issues.cask.co/browse/CDAP-15642
In the scope of this PR:
Created PubSub integration tests

CDAP-15642 Pubsub integration tests coverage

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/DataprocETLTestBase.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleCloudBigtableTest.java
pom.xml

JIRA: 
- https://issues.cask.co/browse/CDAP-15643 
- https://issues.cask.co/browse/CDAP-15734
- Bigtable integrated tests added.
- Added support all data types in integration tests for BigTable
- Added property "google.application.bigtable.instance" to specify bigtable instance for tests

CDAP-15643 & CDAP-15734 Support all data types in BigTable Sink & Source integration tests

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java
pom.xml

JIRA: https://issues.cask.co/browse/CDAP-15644
* BigQuery basic integration tests have been added.

CDAP-15644: Added BigQuery integration tests.

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleCloudSpannerTest.java

JIRA: https://issues.cask.co/browse/CDAP-15735
* Added tests for Array in Spanner plugin

CDAP-15735 Support all data types in integration tests for Spanner

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleCloudSpannerTest.java

Reverts cdapio/cdap-integration-tests#1020

Revert "CDAP-15735 Support all data types in integration tests for Spanner"

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/GoogleBigQueryTest.java

JIRA: https://issues.cask.co/browse/CDAP-15771
* Added support BigQuery bytes type.

CDAP-15771: Added check for BigQuery bytes type.

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/ETLTestBase.java

This change is needed due to https://github.com/cdapio/cdap/pull/11546 and https://github.com/cdapio/cdap/pull/11568.
Otherwise:
```
java.io.IOException: 500: Unable to validate session
at io.cdap.cdap.client.util.RESTClient.execute(RESTClient.java:132)
at io.cdap.cdap.client.util.RESTClient.execute(RESTClient.java:82)
at io.cdap.cdap.app.etl.ETLTestBase.installPluginFromMarket(ETLTestBase.java:193)
at io.cdap.cdap.app.etl.batch.HivePluginTest.testHivePlugins(HivePluginTest.java:76)
```

Fix HivePluginTest (installing from market)

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/ETLMapReduceTest.java

the validator plugin was removed, so removing the test as well

remove validator test

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java

JIRA: https://issues.cask.co/browse/PLUGIN-82
- Added new tests to cover dedupe functionality.

PLUGIN-82: Added new tests to cover dedupe functionality.

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudSpannerTest.java

increase amount of time to wait for metrics

CDAP-16604 increase metrics timeout

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java

ITN:
https://builds.cask.co/browse/IT-CLD7-1

Fix broken ITN

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

Jira ticket: https://cdap.atlassian.net/browse/PLUGIN-558

Add integration test for GCSDoneFileMarker

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java

PR: https://github.com/data-integrations/google-cloud/pull/437
JIRA Ticket: https://cdap.atlassian.net/browse/PLUGIN-318

PLUGIN-318: Integration Tests for formats in PubSubSource and PubSubSink 

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/BatchAggregatorTest.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/wrangler/WranglerServiceTest.java
integration-test-remote/src/test/java/io/cdap/cdap/app/fileset/PermissionTest.java

Reverts cdapio/cdap-integration-tests#1100

Revert "Itn failures"

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java

Field validation logic in BigQuery sink pipelines causes a NullPointerException
Jira ticket: https://cdap.atlassian.net/browse/CDAP-17746
Fix PR: https://github.com/data-integrations/google-cloud/pull/590

Integration test for bugfix/CDAP_17746

---

integration-test-remote/src/test/java/io/cdap/cdap/app/fileset/PermissionTest.java

[CDAP-17747] Disable dynamic partitioning checks

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/FieldAdderTest.java

PR: https://github.com/data-integrations/add-field/pull/15
JiraTicket: https://cdap.atlassian.net/browse/PLUGIN-488

Integration test for BugFix PLUGIN-488

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java

Integration Tests for PLUGIN_654: Pub/Sub source fails when subscription is a macro
Fix PR: https://github.com/data-integrations/google-cloud/pull/612
JIRA Ticket: https://cdap.atlassian.net/browse/PLUGIN-654

PLUGIN_654: PubSub-Macro-Subscription-IntegrationTests

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryExecuteTest.java

Integration Tests for PLUGIN-496: Support syntax checking in BigQuery execute plugin.
Fix PR: https://github.com/data-integrations/google-cloud/pull/614
JIRA Ticket: https://cdap.atlassian.net/browse/PLUGIN-496

PLUGIN-496: Support syntax checking in BigQuery execute plugin - Integration Tests.

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java

Integration test for PLUGIN 655: BQ Sink without input schema or table fails with NPE.
Fix PR: https://github.com/data-integrations/google-cloud/pull/611
JIRA Ticket: https://cdap.atlassian.net/browse/PLUGIN-655

PLUGIN 655: BQ Sink without input schema or table fails with NPE.

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/BatchAggregatorTest.java

Integration test for PLUGIN-595 Conditional aggregate functions
Jira ticket: https://cdap.atlassian.net/browse/PLUGIN-595
Fix PR: https://github.com/cdapio/hydrator-plugins/pull/1350

Integration test for PLUGIN-595 Conditional aggregate functions

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java

Disable PubSubTest till CDAP-18241 is fixed

Disable PubSubTest till CDAP-18241 is fixed

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

Temporarily disable failing tests to proceed with testing

Temporarily disable failing tests to proceed with testing

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java
pom.xml

- cherry pick for https://github.com/cdapio/cdap-integration-tests/pull/1131
- Also re-enabling testGCSCopy and testSchemaDetectionOnMultipleFilesWithDifferentSchema

Fix GCSTest#testSchemaDetectionOnMultipleFilesWithDifferentSchema

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudSpannerTest.java

[PLUGIN-987](https://cdap.atlassian.net/browse/PLUGIN-987)

migrate connection in Google Cloud BigQuery and Spanner Tests

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryMultiSinkTest.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQueryTest.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleCloudSpannerTest.java

[PLUGIN-987](https://cdap.atlassian.net/browse/PLUGIN-987)

migrate bigquery-multi-sink-test to run with/without connection

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

[PLUGIN-987](https://cdap.atlassian.net/browse/PLUGIN-987)

modified GCS Tests to run with/without connections

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

Reverts cdapio/cdap-integration-tests#1145 to check why ITN is failing.

Revert "modified GCS Tests to run with/without connections"

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

Reverts cdapio/cdap-integration-tests#1147
Putting it back, since we know cloud-itn is failing due to some other reason.

Revert "Revert "modified GCS Tests to run with/without connections""

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java

Reverts cdapio/cdap-integration-tests#1149

Revert "Temporary change to run tests using Dataproc 1.5"

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java

**Issue**
https://cdap.atlassian.net/browse/PLUGIN-1019
_Tested this on my local sandbox_

test for connection support in bq transformation pushdown

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java

**Issue**
https://cdap.atlassian.net/browse/PLUGIN-1019

Connection support for bq-pushdown

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java

Reverts cdapio/cdap-integration-tests#1168

Revert "Enable PubSubTest"

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java

With write-ahead logs being enabled by default, the streaming pipelines also need checkpoint directory to be specified.
Jira: https://cdap.atlassian.net/browse/CDAP-19318

Add checkpoint directory to pub-sub tests

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

Jira: https://cdap.atlassian.net/browse/PLUGIN-664
PR for code update: https://github.com/data-integrations/google-cloud/pull/1058

[Plugin-664] Add test case for GCS Delete Action

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

Jira: https://cdap.atlassian.net/browse/PLUGIN-664
PR: https://github.com/data-integrations/google-cloud/pull/1060

[PLUGIN-664] Update test for path with special regex character

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

Revert [Plugin-664] Add test case for GCS Delete Action 

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GCSTest.java

Jira: https://cdap.atlassian.net/browse/PLUGIN-664

[PLUGIN-664]Add test for GCS Delete Action

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DLPTest.java

[Cherrypick] update dlp plugin version

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java

JIRA: https://cdap.atlassian.net/browse/CDAP-18281
Issue: At the end of a test case, the pipeline is still running when expected to be stopped. During cleanup, profile is disabled but cannot be deleted because there are still running pipelines associated with it. Due to this test cases after the said test case also fails.
Fix: All the pipelines are cleaned up in the tearDown function of IntegrationTestBase. So for the next test case, all we need to do is to enable the profile if it is disabled for it to run successfully.

CDAP-18281 | Cloud-ITN - Profile deletion fails intermittently

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java

- Stop subscriber in finally block
- Correct GCS path for checkpoint directory

cleanup subscribers on failure and correct checkpoint path

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/DedupAggregatorTest.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/batch/WindowAggregatorTest.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java

This PR contains integration tests for Window Aggregation for Big Query Pushdown.Created https://cdap.atlassian.net/browse/CDAP-20175 for common code refactoring

Integration tests for Window Aggregation

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java

Due to Cloud ITN failure of regex removed WINDOW_ARTIFACT variable as it is used only once

Regex correction for WINDOW_ARTIFACT

---

integration-test-remote/pom.xml
integration-test-standalone/pom.xml
perf-test/pom.xml
pom.xml

Bumped hadoop versions and excluded a few dependencies.

[Dependency Bump] Resolve log4j vulnerability

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java

Cherrypick 6.8 Propagate Service Account Email to Compute Profile

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java

https://cdap.atlassian.net/browse/CDAP-20118 | Adding debug information

[CDAP-20118] Add debug information

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java

Cherrypick 6.7 Propagate Service Account Email to Compute Profile

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/PubSubTest.java

cherry pick for https://github.com/cdapio/cdap-integration-tests/pull/1226

Add additional log for message publish status and fix the check for messages

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java
integration-test-remote/src/test/java/io/cdap/cdap/app/etl/wrangler/WranglerTest.java

Cherry-pick for PR: https://github.com/cdapio/cdap-integration-tests/pull/1234

Add integration tests for Wrangler filtering

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java

Release 69 cherrypick dump pipeline logs

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/DataprocETLTestBase.java

Switch remote tests to use e2 machine types

---

integration-test-remote/src/test/java/io/cdap/cdap/app/etl/gcp/GoogleBigQuerySQLEngineTest.java

[🍒] Skip sqlengine window test cherrypick

---

pom.xml

Cherry-pick of https://github.com/cdapio/cdap-integration-tests/pull/1258

[🍒 ] Update pom.xml to use Sonatype Central Snapshots URL
